environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: "true"
  BINSTAR_TOKEN:
    secure: zW96v77uhbDdArc0805i/CDIvVpZvqCJyJ+WgSE1b65nPLO0nGUwmZ9qshUICIba
  matrix:
    - PYTHON: "C:\\Python36_64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"

matrix:
  fast_finish: true

cache:
  - '%PYTHON%'

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build
  - ps: if (!(Test-Path $env:PYTHON\\Scripts\\conda.exe -PathType Leaf)){ .\\devtools\\ci\\install-miniconda.ps1 }
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -AND $env:APPVEYOR_REPO_TAG_NAME.StartsWith('v')) { $env:conda_upload = 'true' }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda build purge
  - conda clean -y --all
  - rm -rf %PYTHON%/conda-bld/*
  - conda build -c omnia -c bioconda devtools/conda-recipe
  - IF "%conda_upload%"=="true" anaconda -t %BINSTAR_TOKEN% upload %PYTHON%/conda-bld/win-*/ommprotocol-*.tar.bz2 -u insilichem --no-progress --force
  - IF "%conda_upload%"=="true" conda install -y  constructor
  - IF "%conda_upload%"=="true" conda remove -y --force constructor
  - IF "%conda_upload%"=="true" pip install -U --no-deps https://github.com/jaimergp/constructor/archive/jinja-env.zip
  - IF "%conda_upload%"=="true" constructor .

artifacts:
  - path: 'ommprotocol*.exe'
    name: ommprotocol

build: off

deploy:
  provider: GitHub
  release: OMMProtocol-$(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: B/gWNOHhL5VYBLSIfvRA+rJmD9TYP6DcVgXi40AO23ypDUAe0ckpjkuE6TmqYlXS
  artifact: /ommprotocol-.*\.exe/
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
